version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: brink-mysql 
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

    volumes:
      - mysql_brink_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_brink_data:
